apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linux-command.fullname" . }}-linux-command
  labels:
    app: linux-command
  {{- include "linux-command.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.linuxCommand.replicas }}
  selector:
    matchLabels:
      app: linux-command
    {{- include "linux-command.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: linux-command
      {{- include "linux-command.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.linuxCommand.linuxCommandContainer.image.repository }}:{{ .Values.linuxCommand.linuxCommandContainer.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.linuxCommand.linuxCommandContainer.imagePullPolicy
          }}
        name: linux-command-container
        ports:
        - containerPort: 3000
        resources: {{- toYaml .Values.linuxCommand.linuxCommandContainer.resources | nindent
          10 }}